version: '3.9'
services:
  kali-rolling-1:
    build: .
    container_name: kali-1
    hostname: frankenkali-1
    environment:
      DISPLAY: ${IP}:0
    ports:
      - "3389:3389"
    volumes:
      - ~/kali_home:/root/
      - ./scripts/:/root/scripts
      - ./.bashrc:/root/.bashrc
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/kali_home/hosts:/etc/hosts
    command: [ "/root/scripts/init.sh" ]
    stdin_open: true
    tty: true
