version: '3.9'
services:
  kali-rolling:
    build: .
    container_name: kali-linux-default
    hostname: frankenkali
    ports:
      - "3389:3389"
    volumes:
      - ./init.sh:/root/init.sh
      - ./set_pass.expect:/root/set_pass.expect
    command: [ "/root/init.sh" ]
    stdin_open: true
    tty: true
